### ISSUE TITLE
auro-banner: flip the image and text area

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-card#23]
## Is your feature request related to a problem? Please describe.
The banner doesn't allow the image and text to be flipped (image on the left and text on the right)

## Describe the solution you'd like
A way to flip a banner without creating a specific variant that just flips the banner.

## Describe alternatives you've considered
Create an additional variant

## Additional context
![image](https://user-images.githubusercontent.com/5118118/118893662-a6174180-b8b7-11eb-81df-768de8a20297.png)

**Comment by blackfalcon** [comment]
Schedule time to discuss how to support features and look at opportunities for API adjustments.

**Comment by blackfalcon** [comment]
Work on this update is postponed until the competition of a new auro-[image] element. The concept being that it's better to place all the image features into a nested element versus adding complexity to the auro-banner/cards elements.
