### ISSUE TITLE
auro-banner: flexible image size area

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-card#24]
## Is your feature request related to a problem? Please describe.
Currently each variation has a set width for the image slot.  The design team would like the flexibility to have different size images for different implementations.

## Describe the solution you'd like
A way to set the size of the image area and have the text take the remaining space.

## Describe alternatives you've considered
Create a new variant for each design request. Create our own.

**Comment by blackfalcon** [comment]
Schedule time to review feature

**Comment by blackfalcon** [comment]
Work on this update is postponed until the competition of a new auro-[image] element. The concept is that it's better to place all the image features into a nested element versus adding complexity to the auro-banner/cards elements.
