### ISSUE TITLE
auro-banner: image flexibility

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-card#25]
## Is your feature request related to a problem? Please describe.
The current implementation doesn't allow for the image to be centered.  If there is a credit card image for example it is forced to stick at the bottom of the space.

## Describe the solution you'd like
A way to show images centered in the space vs always pinned to the bottom.

## Describe alternatives you've considered
Perhaps creating an auro-background component would be better.

## Additional context
The current setup sometimes requires super large images in order for the to fill the desired space.  And with everything pinned at the bottom by default only images that have the focal point near the bottom or no focal point at all work well here.

**Comment by blackfalcon** [comment]
Schedule time to review the feature.

**Comment by blackfalcon** [comment]
Work on this update is postponed until the competition of a new auro-[image] element. The concept is that it's better to place all the image features into a nested element versus adding complexity to the auro-banner/cards elements.

**Comment by blackfalcon** [comment]
When work is addressed, it is preferred that this and the following issues are added to a single PR. 

* https://github.com/AlaskaAirlines/auro-card/issues/24
* https://github.com/AlaskaAirlines/auro-card/issues/23
