### ISSUE TITLE
Upgrade to latest version of Generator build

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-card#32]
# General Support Request

The current version of auro-card is based on an older version of the WC-Generator. 

## Support request

Update repo to be based on the latest version of Auro's WC-Generator.

## Context

This is a BREAKING CHANGE and the code commit needs to reflect this change.

**Comment by blackfalcon** [comment]
This issue is considered abandoned due to new work being done to replace this version of the element. At this point, it would be considered easier to start with a fresh repo versus retro-fitting this one.

**Comment by Patrick-Daly-AA** [comment]
closing per previous comment and roadmap plan to refactor/rebuild this component.
