### ISSUE TITLE
auro-card: blueprint

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-card#35]
# Blueprint
We need a blueprint for auro-card that matches the features we have currently on our doc site.

## Outline tasks

- [x] anatomy
- [x] color
- [x] typography
- [x] layout
- [x] spacing
- [x] animation/behavior
- [x] variants
- [x] states (hover, focus, active, focus-visible)
- [x] a11y

## Optional

- [x] Competitive analysis
- [x] research
- [x] site audit
- [x] usage audit
- [ ] inspirational work

**Comment by leeejune** [comment]
Blueprint done. Needs review.

https://www.figma.com/file/Qi9dapT6aEd4EQUnWZW6Uz/Card?node-id=322%3A298

**Comment by leeejune** [comment]
Needs mobile exploration.

**Comment by leeejune** [comment]
Blueprint completed. Needs review from @jason-capsule42 

Please view the blueprint in order: top-bottom, left-right.

**Comment by leeejune** [comment]
Edited to better fit engineering needs. Simplified to 4 slots for an image, header, content, and CTA.

Please review @jason-capsule42 

[Link to blueprint](https://www.figma.com/file/Qi9dapT6aEd4EQUnWZW6Uz/Card?node-id=1721%3A7078&t=1Y5UzRVl63QZiPOs-1)

**Comment by leeejune** [comment]
Reviewed by team. @jason-capsule42 @blackfalcon Should I create another issue for next steps? Do we need a dev plan?
