### ISSUE TITLE
auro-card: mobile blueprint

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-card#41]
# Blueprint
We need a blueprint for the mobile/responsive version of auro-card.

## Outline tasks

- [ ] anatomy
- [ ] color
- [ ] typography
- [ ] layout
- [ ] spacing
- [ ] animation/behavior
- [ ] variants
- [ ] states (hover, focus, active, focus-visible)
- [ ] a11y

## Optional

- [ ] Competitive analysis
- [ ] research
- [ ] site audit
- [ ] usage audit
- [ ] inspirational work

**Comment by leeejune** [comment]
https://www.figma.com/file/Qi9dapT6aEd4EQUnWZW6Uz/Card?node-id=1743%3A7172&t=ZfwXy1ioQjOTutvP-4

Blueprint completed.

**Comment by leeejune** [comment]
@jason-capsule42 Please review.

**Comment by leeejune** [comment]
Reviewed by team. @jason-capsule42 @blackfalcon Should I create another issue for next steps? Do we need a dev plan?

**Comment by blackfalcon** [comment]
Product was made aware of the completed design work. This and other work defined in the next feature release milestone will be discussed in an upcoming planning meeting depending on priorities.
