### ISSUE TITLE
auro-card dev blueprint

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-card#42]
# General Support Request

After discussion about the card blueprint, developers decided to move towards a simpler solution. The blueprint needs to be edited to accommodate this request. 

## Requirements

- [ ] Outline 4 slots: image, header, content, CTA
- [ ] Anatomy
- [ ] Variants
- [ ] Spacing

**Comment by Patrick-Daly-AA** [comment]
Blueprint is done, but not yet on the doc site.

With the impending refactor of the component, we will need to create a new issue to rebuild the blueprint and publish to the doc site.
