### ISSUE TITLE
auro-card: 3.0 - Base component.

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-card#44]
## Is your feature request related to a problem? Please describe.
Create the basic version of `auro-card` 3.0 based off of the updated blueprint.

Blueprint: https://www.figma.com/file/Qi9dapT6aEd4EQUnWZW6Uz/Card?node-id=1721%3A5834&mode=dev

## Describe the solution you'd like
There will be two variations of this version, one with a border and one without.

## Describe alternatives you've considered
Create custom html cards any time we need them.

## Additional context
This is the first story of a full rewrite of this component.  All current API features will be deprecated and follow up stories will be created for future features.

**Comment by DukeFerdinand** [comment]
working on this!

**Comment by rsstdd** [comment]
Working on this as well
