### ISSUE TITLE
Inaccessible and poor example 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-card#49]
## Describe the bug

The Billboard Background Image Slot example is not accessible and a poor example

## To Reproduce
1. Go to 'https://auro.alaskaair.com/components/auro/banner#gsc.tab=0'
2. See Background image slot
3. See error

## Expected behavior
Update the example so that the text in the demo is readable and accessible 

## Screenshots
<img width="1125" alt="Screen Shot 2024-01-05 at 8 04 49 PM" src="https://github.com/AlaskaAirlines/auro-card/assets/181089/0bd998ee-324a-4df3-8210-03f0f0a1f97a">

## Exi criteria 

This issue can be closed once the demo has been updated so that the text is clearly visible within the banner and accessible.

**Comment by pgm369** [comment]
@Patrick-Daly-AA  I validated this is a bug since it is reproducible in the docsite!

**Comment by blackfalcon** [comment]
I am electing to close this issue as these elements are under redevelopment.
