### ISSUE TITLE
auro-banner: content overflows at intermediate breakpoints

### ISSUE THREAD

**Issue by littleninja** [AlaskaAirlines/auro-card#7]
## Describe the bug
On intermediate breakpoints (screenshots are around ~700-800px width), content can overflow and be clipped. If there are known limits or recommendations, maybe this would be helpful to include in the component documentation.

## To Reproduce
See CodePen: https://codepen.io/little_ninja/pen/NWbBvEE

## Expected behavior
Either (ideal) banner scales or otherwise handles content so that it does not overflow, or perhaps document recommended authoring limits.

## Screenshots

![button clipped on oneworld hub page](https://user-images.githubusercontent.com/4391579/110034927-deaf7200-7cef-11eb-84e5-83ad684837f9.png)
![title clipped in codepen example](https://user-images.githubusercontent.com/4391579/110035815-faffde80-7cf0-11eb-9cbf-94697eade33c.png)

## Desktop (please complete the following information):
 - OS: MacOS 11.2.1
 - Browser: Firefox 86.0
 - Version(auro-card): 1.0.4

## Additional context
n/a

**Comment by blackfalcon** [comment]
I don't know which came first, but these seem related. https://github.com/AlaskaAirlines/auro-card/pull/6

**Comment by braven112** [comment]
They are related.  And #6 addresses the issue we saw the the ow implementation.  While doing additional texting I did discover that the max-height for the billboard can affect the other styles if there is a lot more text.  I'll have another PR that will address that issue.

**Comment by braven112** [comment]
PR for this one is ready to go https://github.com/AlaskaAirlines/auro-card/pull/8/commits
